config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#landing"

  get '/home', to: "pages#home"
  get '/profile', to: "pages#profile"
  get "/prompt", to: "prompts#sample"
  get "/graph-data", to: "logbooks#data"

  resources :logbooks do
    resources :recommendations, only: %i[show]
    resources :playlists, only: %i[show]
    resources :books, only: %i[show]
    resources :journals, only: %i[new create edit update]

    collection do
      get "date/:date", action: :date, as: :date
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :emoji
end

app/models/emoji.rb
class Emoji < ApplicationRecord
  has_many :logbooks
  has_many :playlists
  has_many :books, dependent: :destroy
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :logbook
  belongs_to :prompt, optional: true
end

app/models/logbook.rb
class Logbook < ApplicationRecord
  has_one_attached :image

  belongs_to :emoji
  belongs_to :user

  has_many :journals, dependent: :destroy
  has_one :recommendation
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :emoji
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  has_many :journals
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :logbook
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @logbook = Logbook.find(params[:logbook_id])
    @recommendations = @logbook.emoji.books
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_logbook, only: %i[new create edit update]
  before_action :set_journal, only: %i[edit update]

  def new
    @journal = Journal.new
    @sample_prompt = Prompt.all.sample
  end

  def create
    @journal = Journal.new(journal_params)
    @journal.logbook = @logbook
    @journal.date = Date.today
    @journal.time = Time.now

    if @journal.save
      redirect_to logbook_path(@journal.logbook), notice: 'Journal was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @journal.update(journal_params)
      redirect_to logbook_path(@journal.logbook), notice: 'Journal was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_logbook
    @logbook = Logbook.find(params[:logbook_id])
  end

  def set_journal
    @journal = Journal.find(params[:id])
  end

  def journal_params
    params.require(:journal).permit(:content, :prompt_id)
  end
end

app/controllers/logbooks_controller.rb
class LogbooksController < ApplicationController
  before_action :set_logbook, only: %i[show edit update destroy]

  def index
    @logbooks = Logbook.where(user: current_user).order("date DESC")
  end

  def show; end

  def new
    @logbook = Logbook.new
  end

  def create
    @logbook = Logbook.new(logbook_params)
    @logbook.user = current_user
    @logbook.date = Date.today
    @logbook.time = Time.now

    if @logbook.save
      redirect_to edit_logbook_path(@logbook), notice: 'Log was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @logbook.update(logbook_params)
      if params[:submit] == "📖"
        redirect_to logbook_book_path(@logbook)
      elsif params[:submit] == '🎵'
        redirect_to logbook_playlist_path(@logbook)
      elsif params[:submit] == '💾'
        redirect_to logbooks_path
      end
      recommendations_controller = RecommendationsController.new
      recommendations_controller.request = request
      recommendations_controller.response = response
      recommendations_controller.create
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def date
    @date = Date.parse(params[:date])
    @logbooks = Logbook.where(
      "EXTRACT(YEAR from created_at) = ? and EXTRACT(MONTH from created_at) = ? and EXTRACT(DAY from created_at) = ?", @date.year, @date.month, @date.day
    )
  end

  def data
    current_date = Date.today
    start_of_week = current_date.beginning_of_week
    end_of_week = current_date.end_of_week
    @current_logbooks = Logbook.where(date: start_of_week..end_of_week).where(user_id: current_user.id)
    @data = {}
    @current_logbook_day = @current_logbooks.group_by { |e| e.date.strftime("%a") }
    @current_logbook_day.each_value do |array_logbooks|
      max_value = 0
      array_logbooks.each do |logbook|
        max_value = logbook.emoji.value if logbook.emoji.value >= max_value
      end
      @data[@current_logbook_day.key(array_logbooks)] = max_value
    end

    respond_to do |format|
      format.json
    end
  end

  private

  def set_logbook
    @logbook = Logbook.find(params[:id])
  end

  def logbook_params
    params.require(:logbook).permit(:summary, :image, :emoji_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @logbook = Logbook.where(user: current_user).last
  end

  def profile
    @logbooks = Logbook.where(user: current_user)
    @this_week = @logbooks.where(created_at: (Date.today - 7)..(Date.tomorrow))
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def show
    @logbook = Logbook.find(params[:logbook_id])
    @recommendations = @logbook.emoji.playlists
  end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  def sample
    @sample = Prompt.all.sample

    respond_to do |format|
      format.text do
        render partial: "sample", locals: { sample: @sample }, formats: [:html]
      end
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def create
    @logbook = Logbook.find(params[:id])
    @recommendation = Recommendation.new
    @recommendation.logbook = @logbook
    @recommendation.logbook.emoji = @logbook.emoji

    @recommendation.save
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/show.html.erb
<div class="h-container layer-recommendation">
  <div class="container mt-5">
    <div class="recommendations-header mb-4">
      <h1>Books for you today,</h1>
      <p>since you're feeling <em><%= @logbook.emoji.title %></em></p>
      <p><em>you're doing great by staying in touch with your feelings </em></p>
    </div>
    <% @recommendations.each do |recommendation| %>
      <%= link_to recommendation.url do %>
        <div class="card-product m-3">
          <%= image_tag(recommendation.image_url.html_safe) %>
          <div class="card-product-infos">
            <h2><%= recommendation.title %></h2>
            <p><%= recommendation.author %></p>
            <h5><%= recommendation.description.truncate(115) %></h5>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/journals/edit.html.erb
<h1>Hi from edit journal!</h1>

<%= simple_form_for [@logbook, @journal] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :prompt, label_method: :content %>
    <%= f.input :content %>
    <%= f.input :date, as: :hidden, input_html: { value: Date.today } %>
    <%= f.input :time, as: :hidden, input_html: { value: Time.now } %>
  </div>

  <div class="form-actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


<%= link_to "Homepage", home_path %>
<%= link_to "Back to this log", logbook_path(@logbook) %>

app/views/journals/new.html.erb
<div class="h-container layer-journal">
  <div class="journal-container">
    <h1>Today: <br><%= Date.today.strftime("%d %b, %Y") %></h1>

    <%= simple_form_for [@logbook, @journal] do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div data-controller="shuffle-prompt">
        <div class="form-inputs">
          <div style="height: 4rem">
            <p data-shuffle-prompt-target="prompt"><%= @sample_prompt.content %></p>
          </div>
          <%= f.input :prompt_id, as: :hidden, input_html: { value: @sample_prompt.id, data: {shuffle_prompt_target: "promptInput" } } %>
          <div class="d-flex">
            <div>
              <button data-action="click->shuffle-prompt#shuffle", class="btn btn-secondary mb-3" >
                <i class="fa-solid fa-shuffle"></i> New prompt
              </button>
            </div>
            <div class="px-2">
              <button data-action="click->shuffle-prompt#clear", class="btn btn-outline-secondary mb-4" >
                <i class="fa-solid fa-xmark"></i>
              </button>
            </div>
          </div>
          <%= f.input :content, label: "Write here" %>
        </div>
      </div>

      <div class="form-actions d-flex justify-content-end">
        <%= f.submit 'Save', class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PathFinder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'bootstrap.min.js' %>
  </head>

  <body class="body-view">
    <%= yield %>
    <%= render "shared/navbar" if user_signed_in? && action_name != "landing" %>
    <%# <%= render "shared/flashes" %>
  </body>
</html>

app/views/layouts/uikit.html.erb
  <button type="button" class="btn btn-outline-secondary shadow-sm rounded">Back</button>
  <button type="button" class="btn btn-outline-secondary text-muted shadow-sm" >Submit</button>

  <div class="card border-light my-3" style="max-width: 18rem;">
    <div class="card-header">09/07/2023</div>
    <div class="card-body overflow-scroll">
      <h2 class="card-title">He broke my heart</h2>
      <p class="card-text">Raw ache within, shattered dreams haunt. Echoes of laughter linger. Embracing pain's lessons, seeking solace in time's embrace. Raw ache within, shattered dreams haunt. Echoes of laughter linger. Embracing pain's lessons, seeking solace in time's embrace.</p>
    </div>
  </div>
</div>

app/views/logbooks/date.html.erb
<div class="container mt-3 text-center">
  <h1><%= @date %></h1>
  <% if @logbooks.empty? %>
    <div class="container mt-5">
      <img src="https://source.unsplash.com/2Ts5HnA67k8" alt="" width="200" class="shadow-lg rounded-circle my-3" >
      <p>Empty...</p>
    </div>
  <% else %>
    <div class="card mt-2">
      <div class="shadow card-body">
        <ul>
          <% @logbooks.each do |log| %>
            <li><%= log.summary %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/logbooks/edit.html.erb
<div class="h-container layer_edit">
  <div class="mood-check edit_margin">

    <%= simple_form_for(@logbook) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <h3>How was your day?</h3>

      <div class="d-flex justify-content-between pt-3 pb-2">
        <% Emoji.all.each do |emoticon| %>
          <%= f.label :emoji_id, emoticon.title do %>
          <%= f.radio_button :emoji_id, emoticon.id %>
          <h1><%= emoticon.image.html_safe %></h1>
          <% end %>
        <% end %>
      </div>


        <p><%= f.input :summary, label: "Today's note" %></p>
        <p><%= f.input :image, as: :file, label: "Today's photo" %></p>
        <%= f.association :user, as: :hidden, input_html: { value: current_user.id }  %>
      </div>

      <div class="form-actions d-flex justify-content-around">
        <%= submit_tag '📖', name: 'submit', class: "btn btn-secondary rounded text-muted shadow-sm", style: "font-size:20px;" %>
        <%= submit_tag '💾', name: 'submit', class: "btn btn-secondary rounded text-muted shadow-sm", style: "font-size:20px;" %>
        <%= submit_tag '🎵', name: 'submit', class: "btn btn-secondary rounded text-muted shadow-sm", style: "font-size:20px;" %>
      </div>

    <% end %>
  </div>
</div>

app/views/logbooks/index.html.erb
<div class="h-container layer3">
  <div class="text-center mt-5">
    <h1>Your path</h1>
  </div>
  <div class="logbook-container">
        <% @logbooks.each do |logbook| %>
          <%= link_to logbook_path(logbook) do %>
            <div class="journal-card">
              <div style = "font-weight: lighter;">
                <%= logbook.date.strftime("%d %b, %Y") if logbook.date %>
                <br>
                <em><%= logbook.emoji.title %></em>
                <%= logbook.emoji.image.html_safe %>
              </div>
              <%= logbook.summary %>
              <%= cl_image_tag logbook.image.key, class:"card-img-top journal-image", crop: :fill if logbook.image.attached?%>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/logbooks/new.html.erb
<div class="landing-container landing-bg-image">
  <div class="landing-welcome">
    <h1>pathFinder.</h1>
    <br>
    <h2>How was your day?</h2>
  </div>
  <div class="w-100">
    <%= simple_form_for(@logbook) do |f| %>
      <div class="carousel slide mt-2 pt-1" id="emojiCarousel" data-controller="carousel">
        <div class="carousel-inner">
          <% Emoji.all.each_with_index do |emoji, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>"
                  data-target="carousel.emoji"
                  data-action="click->carousel#selectEmoji"
                  data-emoji-id="<%= emoji.id %>">
              <label>
                <h1 style="font-size:200px;"><%= emoji.animation.html_safe %></h1>
                <%= radio_button_tag 'logbook[emoji_id]', emoji.id, false, id: nil, style: 'display: none;' %>
              </label>
            </div>
          <% end %>

          <a class="carousel-control-prev" href="#emojiCarousel" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </a>
          <a class="carousel-control-next" href="#emojiCarousel" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/logbooks/show.html.erb
<div class="h-container layer4">
  <div class="journal-header-container">
    <h1><span><%= @logbook.date.strftime("%d of %B") %><br><%= @logbook.time.strftime("%I:%M %p") %></span></h1>
  </div>
  <div class="journal-entry">
    <h5><%= @logbook.emoji.title %></h5>
    <%= @logbook.emoji.image.html_safe %>
    <p><%= @logbook.summary %></p>
    <%= cl_image_tag(@logbook.image.key, class:"card-img-top journal-image", crop: :fill) if @logbook.image.attached? %>
    <br>
    <% @logbook.journals.each do |journal| %>
      Journal entry at <%= journal.created_at.strftime("%I:%M %p") %>:
      <p><%= journal.prompt.content if journal.prompt %></p>
      <p><%= journal.content %></p>
      <div class="d-flex justify-content-between">
      <%= link_to "Edit journal", edit_logbook_journal_path(@logbook, journal) %>
    <% end %>
    <%= link_to "Update", edit_logbook_path(@logbook) %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="wrap">
  <div class="h-container home-bg">
    <header class="top">
      <h1>Welcome, <%= current_user.first_name %> 💜</h1>
      <p><%= Date.today.strftime("%d of %B, %Y") %></p>
      <div class="banner-text">
        <p><em>Chi va piano, va sano e va lontano</em> <br>
          "Who goes slowly, goes safely and goes far"</p>
      </div>
    </header>

    <div class="favorites-container">
      <h2>What do you need today?</h2>
      <div class="notification-lg">
        <p>
          <strong>
            <i class="fa-solid fa-bell" style="color: #02394a;"></i>
            Activities Today:
          </strong>
            Meditation and Relaxation
        </p>
        <small>8:00pm</small>
      </div>

      <div class="notification-sm">
        <div class="heart">
          <i class="fa-solid fa-heart" style="color: #ccdbdc;"></i>
        </div>
        <div class="activities-container">
          <img src="http://co0kie.github.io/codepen/mindful/buddhist-yoga-pose.svg" alt="">
          <p><strong>Vinyasa <br>Yoga</strong></p>
        </div>
      </div>

      <%= link_to new_logbook_journal_path(@logbook) do %>
        <div class="notification-sm">
          <div class="heart">
            <i class="fa-solid fa-heart" style="color: #ccdbdc;"></i>
          </div>
          <div class="activities-container">
            <%= image_tag "journal-home.png", alt: "", style:"width:40px; padding-right:10px;"%>
            <p><strong>Mindful Journaling</strong></p>
          </div>
        </div>
      <% end %>

      <%= link_to logbook_book_path(@logbook, @logbook.emoji.book_ids) do %>
        <div class="notification-sm">
          <div class="heart">
            <i class="fa-regular fa-heart" style="color: #ccdbdc;"></i>
          </div>
          <div class="activities-container">
            <%= image_tag "book.png", alt: "" %>
            <p><strong>Book <br> Library</strong></p>
          </div>
        </div>
      <% end %>

      <%= link_to logbook_playlist_path(@logbook, @logbook.emoji.playlist_ids) do %>
        <div class="notification-sm">
          <div class="heart">
            <i class="fa-solid fa-heart" style="color: #ccdbdc;"></i>
          </div>
          <div class="activities-container">
            <%= image_tag "spotify.png", alt: "", style:"width:40px; padding-right:10px;"%>
            <p><strong>Playlists of <br>the Moment</strong></p>
          </div>
        </div>
      <% end %>
    </div>

<!--Waves Container-->
    <div>
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
      viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="parallax">
          <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(164, 170, 218, 0.7)" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(164, 170, 218, 0.5)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(164, 170, 218, 0.3)" />
          <use xlink:href="#gentle-wave" x="48" y="7" fill="#a4aada" />
        </g>
      </svg>
    </div>
<!--Waves end-->
  </div>
</div>

app/views/pages/landing.html.erb
<div class="landing-container landing-bg-image flex-grow-1">
  <div class="landing-welcome">
    <h1>pathFinder.</h1>
    <br>
    <p class="lead">Do not go where the path may lead,</p>
    <p>go instead where there is no path and leave a trail</p>
  </div>

  <div class="blob">
    <svg viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" id="blobSvg">
      <defs>
        <linearGradient id="gradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" style="stop-color: rgb(180, 154, 204);"></stop>
          <stop offset="100%" style="stop-color: rgb(150, 197, 223);"></stop>
        </linearGradient>
      </defs>
      <path fill="url(#gradient)">
        <animate attributeName="d"
          dur= "10000ms"
          repeatCount= "indefinite"
          values="M438,303.5Q397,357,352,391Q307,425,250,425.5Q193,426,129.5,
          404.5Q66,383,71.5,316.5Q77,250,80.5,189.5Q84,129,133.5,87Q183,45,
          249.5,46Q316,47,354,97Q392,147,435.5,198.5Q479,250,438,303.5Z;

          M426,312Q420,374,359.5,387.5Q299,401,236.5,442.5Q174,484,139,420Q104,
          356,87,303Q70,250,71,185Q72,120,123,68.5Q174,17,241,44.5Q308,72,
          355.5,105.5Q403,139,417.5,194.5Q432,250,426,312Z;

          M439,323Q451,396,377.5,406.5Q304,417,250.5,415Q197,413,132.5,
          397.5Q68,382,66,316Q64,250,65,183Q66,116,121,69Q176,22,242,47.5Q308,
          73,351.5,109Q395,145,411,197.5Q427,250,439,323Z;

          M422.5,312.5Q422,375,363,395.5Q304,416,252.5,408.5Q201,401,157.5,
          375Q114,349,58.5,299.5Q3,250,29.5,179.5Q56,109,123.5,88Q191,67,248,
          73.5Q305,80,378.5,91.5Q452,103,437.5,176.5Q423,250,422.5,312.5Z;

          M445,310Q415,370,358,388.5Q301,407,240.5,436Q180,465,151.5,403.5Q123,
          342,99,296Q75,250,75.5,187Q76,124,129,83Q182,42,240.5,70.5Q299,99,
          338.5,128Q378,157,426.5,203.5Q475,250,445,310Z;

          M438,303.5Q397,357,352,391Q307,425,250,425.5Q193,426,129.5,
          404.5Q66,383,71.5,316.5Q77,250,80.5,189.5Q84,129,133.5,87Q183,45,
          249.5,46Q316,47,354,97Q392,147,435.5,198.5Q479,250,438,303.5Z">
        </animate>
      </path>
    </svg>
  </div>

  <%= link_to new_logbook_path, class: "blob" do %>
    <svg viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" id="blobSvg">
      <defs>
        <linearGradient id="gradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" style="stop-color: rgb(180, 154, 204);"></stop>
          <stop offset="100%" style="stop-color: rgb(150, 197, 223);"></stop>
        </linearGradient>
      </defs>
      <path fill="url(#gradient)">
        <animate attributeName="d"
          dur= "10000ms"
          repeatCount= "indefinite"
          values="M438,303.5Q397,357,352,391Q307,425,250,425.5Q193,426,129.5,
          404.5Q66,383,71.5,316.5Q77,250,80.5,189.5Q84,129,133.5,87Q183,45,
          249.5,46Q316,47,354,97Q392,147,435.5,198.5Q479,250,438,303.5Z;

          M426,312Q420,374,359.5,387.5Q299,401,236.5,442.5Q174,484,139,420Q104,
          356,87,303Q70,250,71,185Q72,120,123,68.5Q174,17,241,44.5Q308,72,
          355.5,105.5Q403,139,417.5,194.5Q432,250,426,312Z;

          M439,323Q451,396,377.5,406.5Q304,417,250.5,415Q197,413,132.5,
          397.5Q68,382,66,316Q64,250,65,183Q66,116,121,69Q176,22,242,47.5Q308,
          73,351.5,109Q395,145,411,197.5Q427,250,439,323Z;

          M422.5,312.5Q422,375,363,395.5Q304,416,252.5,408.5Q201,401,157.5,
          375Q114,349,58.5,299.5Q3,250,29.5,179.5Q56,109,123.5,88Q191,67,248,
          73.5Q305,80,378.5,91.5Q452,103,437.5,176.5Q423,250,422.5,312.5Z;

          M445,310Q415,370,358,388.5Q301,407,240.5,436Q180,465,151.5,403.5Q123,
          342,99,296Q75,250,75.5,187Q76,124,129,83Q182,42,240.5,70.5Q299,99,
          338.5,128Q378,157,426.5,203.5Q475,250,445,310Z;

          M438,303.5Q397,357,352,391Q307,425,250,425.5Q193,426,129.5,
          404.5Q66,383,71.5,316.5Q77,250,80.5,189.5Q84,129,133.5,87Q183,45,
          249.5,46Q316,47,354,97Q392,147,435.5,198.5Q479,250,438,303.5Z">
        </animate>
      </path>
    </svg>
  <% end %>
</div>

app/views/pages/profile.html.erb
<div class="text-center layer-profile pt-5">

  <h1>Hi <%= current_user.first_name %> 😘</h1>

  <div class="container">
    <div class="journal-card my-4">
      <p>Weekly Wellcheck Graph:</p>
      <canvas data-controller="profile-chart" id="chart" data-profile-target="chart"></canvas>
    </div>

    <div data-controller="profile">
      <div class="calendar-container my-3 text-center" data-profile-target="calendar">
        <div class="class">
          <p>Monthly Log Calendar:</p>
        </div>

        <div class="container mb-5 d-flex-none">
          <%= month_calendar do |date| %>
            <% if @logbooks.select { |logbook| logbook.date == date } != [] %>
            <% logbook = Logbook.where(date: date) %>
              <%= link_to logbook_path(logbook.last.id) do %>
                <div class="link_date"><%= date.day %></div>
              <% end %>
            <% else %>
              <%= date.day %>
            <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </div>

</div>









<%# <% @logbooks.each do |logbook| %>
  <%# <%= logbook.emoji.value %>
<%# <% end %>

app/views/playlists/show.html.erb
<div class="h-container layer-recommendation">
  <div class="container mt-5">
    <div class="recommendations-header mb-3">
      <h1 class="mb-4">Playlists of the hour:</h1>
      <p>since you're feeling <em><%= @logbook.emoji.title %></em></p>
      <p><em>you're doing great by staying in touch with your feelings </em></p>
    </div>
    <% @recommendations.each do |recommendation| %>
      <div class="p-1">
        <%= recommendation.image_url.html_safe %>
      </div>
    <% end %>
  </div>
</div>

app/views/prompts/_sample.html.erb
<p data-shuffle-prompt-target="prompt" data-prompt-id="<%= sample.id %>"><%= sample.content %></p>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to home_path do %>
    <i class="fa-solid fa-house" style="color: #CCDBDC;"></i>
  <% end %>
  <%= link_to new_logbook_path do %>
    <i class="fa-solid fa-face-smile-wink" style="color: #ccdbdc;"></i>
  <% end %>
  <%= link_to logbooks_path do %>
    <i class="fa-solid fa-book-open" style="color: #ccdbdc;"></i>
  <% end %>
  <%= link_to profile_path do %>
    <i class="fa-solid fa-user" style="color: #CCDBDC;"></i>
  <% end %>
</div>